# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8311dd4f8f4997ec582a68c82e7f5ab0f7a8b7ce2e8f0683f330c19908e95f53727dc504af00f60ce3b89ce970e9f16d9abf81e839dc64ff4f8b7c8570578afa

test:
  secret_key_base: 772c63b1bf1271f2dfe0d1bee6008d510d8d8457cce44c155d044bae26383877b14feb7e67b4851c9023dc88d6a8a56a796333276b5a64d67085febff19f49fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
