# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5e9f3c444416caab3d78e76a47a09daded6d4ad98302b199ca014657d1b535498dfe0384a24324eccce939e87ad23079fbdf6d1306fd81a943e023d74c80491

test:
  secret_key_base: 19fb138c0826bc3b1e991cb67d3b64eedf0a119dafe6c634551b548fc50f68d920a347a5d1938e8ec1f1c2bff7111b1ffc4ab8f846cbd6bb6fca85fdd6b54290

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
